add: pek2024 session watch page
cniajp/cnia.io pull request #126
Opened 2024-07-04 06:47 UTC by ishikawa-pro

2024-07-04 06:51 UTC, ishikawa-pro commented on astro.config.mjs
react integration を入れた時に自動で書き換わってっぽいですが、基本的には react integration の設定が加わっただけです

2024-07-04 06:51 UTC, ishikawa-pro commented on src/components/pek2024/LivePlayer.tsx
> +  ] = useState<Track>('Track A');
どの track を active にしているかを状態管理

2024-07-04 06:51 UTC, ishikawa-pro commented on src/components/pek2024/LivePlayer.tsx
> +          src={YOUTUBE_URLS[track]}
選択中の track に応じて youtube の url を切り替える

2024-07-04 07:04 UTC, jacopen requested changes
ありがとうございます！良い感じです

二点きになったことです

1. 動画サイズ、もっと大きくてもいいかなと思いました。このくらいのサイズで
![CleanShot 2024-07-04 at 16 01 31](https://github.com/cniajp/cnia.io/assets/79102/a6e17cc2-0d6f-4c5e-9ffe-80c70eac403a)

2. autoplayつけてほしいです
![CleanShot 2024-07-04 at 16 03 57](https://github.com/cniajp/cnia.io/assets/79102/93ef501f-460a-44ed-96a1-be94cdbeecb3)

2024-07-05 14:16 UTC, jacopen requested changes
追加で要望です！

トラックごとのハッシュタグが `#PEK2024_A` `#PEK2024_B` と決まりました。
画面上にこのハッシュタグ情報も出したいです。

トラック切り替えボタンのところに 
```
Track A
(#PEK2024_A)
```
 と表記するのが良いかも、と思いました。もし綺麗にハマらない場合は他の場所に表記でも良いです

2024-07-06 16:25 UTC, tanayan299 approved these changes
LGTMですが、Xのポストボタンを押したときに不要な `#` が入ってしまうのが少し悩ましいですね。

少しドキュメントなど見てみたのですが、`button_hashtag=...` の仕様っぽいのでしょうがないかな…

2024-07-07 09:13 UTC, jacopen approved these changes

2024-07-07 09:20 UTC, merged