CNIA og:image 用画像を追加
cniajp/cnia.io pull request #15
Opened 2024-02-25 13:35 UTC by tanayan299

2024-02-25 14:08 UTC, ishikawa-pro commented on src/config.mjs
> +import defaultImage from '../public/cnia_ogp.png';
preview で確認したら画像が出てないので、ここも import 文だとうまくいかないかもです。

<img width="628" alt="image" src="https://github.com/cniajp/cnia.io/assets/12871716/c33e31aa-f464-48ef-bff4-8c3e23df77aa">

ここと同じような処理がいるかも 🤔 
https://github.com/cniajp/cnia.io/blob/main/src/layouts/pek2024/BaseLayout.astro#L9-L10

2024-02-25 14:10 UTC, jacopen commented
OGPはこことかでも確認できます
https://rakko.tools/tools/9/

<img width="838" alt="image" src="https://github.com/cniajp/cnia.io/assets/79102/d99842d6-cd16-464b-a74c-d1623a578dc2">
上手く出てないねー

ブラウザではこういうエラー
<img width="1055" alt="image" src="https://github.com/cniajp/cnia.io/assets/79102/c1d2d6c9-a653-4866-8e9c-3ee1c766d88e">

webp...?何故だろう

2024-02-25 14:24 UTC, ishikawa-pro commented
import していることで、 build 時に画像の最適化が走ったりして、うまく行ってなさそうなので、一旦 [ここ](https://github.com/cniajp/cnia.io/blob/main/src/layouts/pek2024/BaseLayout.astro#L9-L10) と同じように、 import せずに path をハードコードするのがいいかもです。
<img width="638" alt="image" src="https://github.com/cniajp/cnia.io/assets/12871716/856aef0c-5198-49fd-aec9-6a2c571aebc1">

2024-02-25 14:36 UTC, tanayan299 commented
@cniajp/website 
ハードコードに修正しました！
PEK2024の画像を指定したときは表示されたので、おそらく大丈夫なはずです。

2024-02-29 06:56 UTC, jacopen requested changes
うーん、まだダメっぽいです
![CleanShot 2024-02-29 at 15 55 22](https://github.com/cniajp/cnia.io/assets/79102/d2ff9eef-45a8-49e1-a004-90eda539b930)

404エラー
![CleanShot 2024-02-29 at 15 55 49](https://github.com/cniajp/cnia.io/assets/79102/948b93fa-8053-4fe2-a5e7-f70391468e8c)

2024-03-02 09:39 UTC, tanayan299 commented
ハードコードに変更したので、画像の参照パスが `https://www.cnia.io/cnia_ogp.png` になります。
この画像パスは本PRに含まれているのでPreviewURLではOGP表示されないです。

PEK2024の画像を指定していた時のPreviewURLではOGPが表示されていたので、おそらく大丈夫だろうと踏んでいます。
https://1a383b96.cnia-io.pages.dev/

2024-03-02 10:12 UTC, ishikawa-pro commented
とりえあず path が合ってそうなので大丈夫だとは思います。
<img width="484" alt="image" src="https://github.com/cniajp/cnia.io/assets/12871716/422c482e-0b35-4c98-9b93-71f31a42cd96">

2024-03-02 10:13 UTC, ishikawa-pro approved these changes

2024-03-02 10:20 UTC, merged