CFP募集ページの追加
cniajp/cnia.io pull request #21
Opened 2024-03-02 20:15 UTC by tanayan299

## 概要
- CFP募集開始に向けて、Componentを追加

## 残項目
- CFP募集要項ページのリンク記載
- (Webサイト内で遷移する場合は) CFP募集ページ本体
- CFP申し込みページ用のリンク

2024-03-20 02:31 UTC, ishikawa-pro commented on src/components/common/SocialShare.astro
> +  </button> -->
消しちゃいましょうか

2024-03-20 02:31 UTC, ishikawa-pro commented on src/pages/pek2024/sessions/[id].astro
> +const { id } = Astro.params;
getStaticPaths 内の sessionsData をスコープの外から参照してて、ちょっと危険な感じがしました。

↓のように fetch した session 自体も props に入れて return すると、
```ts
  return sessionsList.map((session) => ({
    params: { id: session.uuid.toString() },
    props: { session },
  }));
```
Astro.props から fetch したデータが取れると思います！
```ts
  const { session } = Astro.props;
```

2024-03-20 11:21 UTC, ishikawa-pro approved these changes

2024-03-20 12:37 UTC, ishikawa-pro approved these changes

2024-03-21 05:21 UTC, ryukez commented on src/pages/pek2024/sessions/guidance.astro
> +            募集は <a href="https://fortee.jp/platform-engineering-kaigi-2024" class="underline-link">fortee</a> 上で行います。
アクセス分析のため、URLをこちらに差し替えをお願いします！
ref: https://pfemjp.slack.com/archives/C06AZJR7K9U/p1710996868215929?thread_ts=1710996002.004289&cid=C06AZJR7K9U

```suggestion
            募集は <a href="https://link.cnia.io/pek2024-cfp-application-form" class="underline-link">fortee</a> 上で行います。
```

2024-03-21 05:23 UTC, ryukez commented on src/pages/pek2024/sessions/guidance.astro
> +          CFPに関するお問い合わせは <a href="https://forms.gle/NZ3d3r4wCBytBmWt9" class="underline-link">フォーム</a> よりお願いいたします
こちらもリンク作成したため差し替えお願いします 🙏 

```suggestion
          CFPに関するお問い合わせは <a href="https://link.cnia.io/pek2024-cfp-inquiry-form" class="underline-link">フォーム</a> よりお願いいたします
```

2024-03-21 05:27 UTC, ryukez commented on src/pages/pek2024/sessions/guidance.astro
> +        href="https://fortee.jp/platform-engineering-kaigi-2024"
こっちもですかね
```suggestion
        href="https://link.cnia.io/pek2024-cfp-application-form"
```

2024-03-22 00:32 UTC, jacopen requested changes
細かいですが、CFP(Call for Proposals)の時点で募集という意味が含まれるのでそこだけ変更要

2024-03-22 00:32 UTC, jacopen commented on src/pages/pek2024/sessions/guidance.astro
> +          <li>2024/03/22 (金) CFP募集開始</li>
```suggestion
          <li>2024/03/22 (金) CFP開始</li>
```

2024-03-22 00:32 UTC, jacopen commented on src/pages/pek2024/sessions/guidance.astro
> +          <li>2024/04/26 (金) 23:59 CFP募集締め切り</li>
```suggestion
          <li>2024/04/26 (金) 23:59 CFP締め切り</li>
```

2024-03-22 03:28 UTC, merged